site_name: My Docs

nav:
  - Home: index.md
  - Course Description: course-description.md
  - Chapters:
      - List of Chapters: chapters/index.md
      - 1. Engineering Field Exploration: chapters/01-engineering-field-exploration/index.md
      - 2. Foundations and Industry Examination: chapters/02-foundations-and-industry-examination/index.md
      - 3. Portfolio and Employment Preparation: chapters/03-portfolio-and-employment-preparation/index.md
      - 4. Problem Statement and Planning: chapters/04-problem-statement-and-planning/index.md
      - 5. Risk Management: chapters/05-risk-management/index.md
      - 6. Work Schedule and Budget: chapters/06-work-schedule-and-budget/index.md
      - 7. Project Proposal Pitch: chapters/07-project-proposal-pitch/index.md
      - 8. Project Execution and Final Presentation: chapters/08-project-execution-and-final-presentation/index.md
  - Learning Graph:
      - Introduction: learning-graph/index.md
      - Course Description Assessment: learning-graph/course-description-assessment.md
      - Concept List: learning-graph/concept-list.md
      - Concept Taxonomy: learning-graph/concept-taxonomy.md
      - Taxonomy Distribution Report: learning-graph/taxonomy-distribution.md
  - MicroSims:
      - Learning Graph Viewer: sims/graph-viewer/index.md
